source 'https://rubygems.org'

gem 'pony'
gem 'rake'
gem 'sinatra', '~>4'
gem 'warden'
gem 'haml', '~>5'
gem 'ratom'
gem 'thin'
gem 'dm-core'
gem 'dm-types'
gem 'dm-migrations'
gem 'dm-sqlite-adapter'
gem 'dm-mysql-adapter'
gem 'rack-protection'
