source 'https://rubygems.org'

gem 'pony'
gem 'rake'
gem 'sinatra'
gem 'warden'
gem 'haml'
gem 'ratom'
gem 'thin'
gem 'dm-core'
gem 'dm-types'
gem 'dm-migrations'
gem 'dm-sqlite-adapter'
gem 'dm-mysql-adapter'
